### ISSUE TITLE
Indentation is wrong when using EditorConfig

### ISSUE THREAD

**Issue by gavinmcfarland** [busterc/vscode-marko-beautify#4]
When used in combination with [EditorConfig](https://editorconfig.org/) the file is formatted with the wrong number of indents.

Using the following EditorConfig

```
root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 4
indent_style = tab
insert_final_newline = true
trim_trailing_whitespace = true
```

Produces the following indentation

```html
<!DOCTYPE html>
<html lang="en">
				<head>
								<meta charset="UTF-8"/>
								<meta name="viewport" content="width=device-width"/>
								<title>
												<${input.title}/>
								</title>
								<!-- <link> tags to include optimized CSS URLs will be included below: -->
								<${input.styles}/>
				</head>
```

Expected result

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8"/>
		<meta name="viewport" content="width=device-width"/>
		<title>
			<${input.title}/>
		</title>
		<!-- <link> tags to include optimized CSS URLs will be included below: -->
		<${input.styles}/>
	</head>
```

**Comment by busterc** [comment]
Your issue is actually with the EditorConfig settings.

What you currently have says "each indention should use 4 tabs" By not providing `tab_width` EditorConfig assumes each tab to also be 4 characters wide:
```yaml
indent_size = 4
indent_style = tab
```

Whereas this says "each indention should use 1 tab, 4 characters wide" and will give you the result you're looking for:
```yaml
indent_size = 1
indent_style = tab
tab_width = 4
```

I hope that helps!

**Comment by gavinmcfarland** [comment]
Hi @busterc that does help thank you and I'm glad I can use your plugin now.

Although from reading the EditorConfig documentation I don't know if that's how it should work.

It says:

> indent_size: a whole number defining the number of columns used for each indentation level and the width of soft tabs (when supported).
> 
> tab_width: a whole number defining the number of columns used to represent a tab character. This defaults to the value of indent_size and doesn't usually need to be specified.

I read this as _indent_size_ is the number of columns to occupy per level of indentation. By default, a tab character equals the size of _indent_size_.

The only reason I mention this is that other formatters don't seem to calculate the indentation in this way. Which is the main reason why this came up. I believe that EditorConfig intends _indent-size__ to be the number of columns to occupy regardless of whether soft tabs or hard tabs are used. This might be offputting to some users who might not think to figure out how to fix it. Feel free to correct me if you think I'm wrong though. Many thanks.
