### ISSUE TITLE
Line removed when style or class used below markup

### ISSUE THREAD

**Issue by gavinmcfarland** [busterc/vscode-marko-beautify#5]
I know I might be in the minority who write their templates like this, but when you have a class or style block below markup all lines are removed.

For example, I would expect the following to be preserved.

```marko
<section class=input.class>
	<${input}/>
</section>

style {
	.test {
		color: red;
	}
}
```

However instead, the output becomes

```marko
<section class=input.class>
	<${input}/>
</section>

<section class=input.class>
	<${input}/>
</section>
style {
	.test {
		color: red;
	}
}
```

**Comment by busterc** [comment]
Actually this should be opened on the official [@marko/prettyprint](https://github.com/marko-js/cli/tree/master/packages/prettyprint) repo; this extension simply includes it as a dependency and exposes it for VSCode users like ourselves.

Also, that's where you should bring up your [EditorConfig parsing issue](https://github.com/busterc/vscode-marko-beautify/issues/4#issuecomment-533925713) (FWIW, I agree with you about how the documentation reads... I just don't use tabs and the workaround suffices in a pinch).

**Comment by gavinmcfarland** [comment]
Ok no problem. Thanks for clarifying that for me. I'll create an issue with [@marko/prettyprint](https://github.com/marko-js/cli/tree/master/packages/prettyprint). Thanks again.
